### ISSUE TITLE
Every package is located in a different folder

### ISSUE THREAD

**Issue by omerl13** [Meir017/node-tgz-downloader#2]
Hi, I am using the downloader to pack all packages and dependencies, and upload them to a private NPM repository. It would be much easier to do so if the downloader would put all the `tgz` files in the same folder, instead of a different folder for each file.
Is it possible to apply this behaviour as an optional argument to the downloader?

**Comment by Meir017** [comment]
This behavior is by design, it uses the same structure as [verdaccio](https://github.com/verdaccio/verdaccio) does

**Comment by omerl13** [comment]
I guess you are using it this way so you can just simply copy the downloaded packages to the verdaccio server. 
I just thought it would be easier to upload the packages by iterating tgz files in one folder and using `npm publish`.
