### ISSUE TITLE
Download Rate Limiting

### ISSUE THREAD

**Issue by deskoh** [Meir017/node-tgz-downloader#39]
Possible to limit download concurrency (e.g. using [p-limit](https://www.npmjs.com/package/p-limit)) as I suspect I'm hitting the rate-limit for npm registry? I need to run several times (as previously downloaded tgz are skipped) before the download ran to completion.

![image](https://user-images.githubusercontent.com/9096984/176802591-2a713393-acd3-44cd-b551-5de7e0baf3b7.png)

Tried monkey-patching the original download https://github.com/Meir017/node-tgz-downloader/blob/9c144bfa7a7acf96cd13ab99e7f7135769f64771/lib/downloader.js#L52-L58

with the following and it worked flawlessly.

```js
  const asyncSequentialDownload = async () => {
    for (let i = 0; i < tarballs.length; i++) {
      const { url, directory } = tarballs[i];
      const position = `${i + 1}/${tarballs.length}`;
      logger(['downloading'.cyan, position], url);
      await _downloadFileWithRetry(url, join(baseDirectory, directory), position, 10);
    }
  }

  return asyncSequentialDownload();
```

**Comment by Meir017** [comment]
@deskoh contributions are more than welcome :)
